package flag

const (
	FlagAll                string = "all"
	FlagAllBoards          string = "all_boards"
	FlagAllWorkspaces      string = "all_workspaces"
	FlagArchived           string = "archived"
	FlagArchivedBoards     string = "archived_boards"
	FlagArchivedWorkspaces string = "archived_workspaces"
	FlagA                  string = "a"
	FlagBoardId            string = "board_id"
	FlagBoardName          string = "board_name"
	FlagB                  string = "b"
	FlagC                  string = "c"
	FlagHelp               string = "help"
	FlagH                  string = "h"
	FlagI                  string = "i"
	FlagK                  string = "k"
	FlagW                  string = "w"
	FlagNewBoardId         string = "new_board_id"
	FlagNewBoardName       string = "new_board_name"
	FlagNewWorkspaceId     string = "new_workspace_id"
	FlagNewWorkspaceName   string = "new_workspace_name"
	FlagN                  string = "n"
	FlagR                  string = "r"
	FlagWorkspaceId        string = "workspace_id"
	FlagWorkspaceName      string = "workspace_name"
)
